require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ZprojectsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # Zproject. As you add validations to Zproject, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    FactoryGirl.attributes_for(:zproject)
  }

  let(:invalid_attributes) {
    {name:''}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ZprojectsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all zprojects as @zprojects" do
      zproject = Zproject.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:zprojects)).to eq([zproject])
    end
  end

  describe "GET #show" do
    it "assigns the requested zproject as @zproject" do
      zproject = Zproject.create! valid_attributes
      get :show, {:id => zproject.to_param}, valid_session
      expect(assigns(:zproject)).to eq(zproject)
    end
  end

  describe "GET #new" do
    it "assigns a new zproject as @zproject" do
      get :new, {}, valid_session
      expect(assigns(:zproject)).to be_a_new(Zproject)
    end
  end

  describe "GET #edit" do
    it "assigns the requested zproject as @zproject" do
      zproject = Zproject.create! valid_attributes
      get :edit, {:id => zproject.to_param}, valid_session
      expect(assigns(:zproject)).to eq(zproject)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new Zproject" do
        expect {
          post :create, {:zproject => valid_attributes}, valid_session
        }.to change(Zproject, :count).by(1)
      end

      it "assigns a newly created zproject as @zproject" do
        post :create, {:zproject => valid_attributes}, valid_session
        expect(assigns(:zproject)).to be_a(Zproject)
        expect(assigns(:zproject)).to be_persisted
      end

      it "redirects to the created zproject" do
        post :create, {:zproject => valid_attributes}, valid_session
        expect(response).to redirect_to(Zproject.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved zproject as @zproject" do
        post :create, {:zproject => invalid_attributes}, valid_session
        expect(assigns(:zproject)).to be_a_new(Zproject)
      end

      it "re-renders the 'new' template" do
        post :create, {:zproject => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested zproject" do
        zproject = Zproject.create! valid_attributes
        put :update, {:id => zproject.to_param, :zproject => new_attributes}, valid_session
        zproject.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested zproject as @zproject" do
        zproject = Zproject.create! valid_attributes
        put :update, {:id => zproject.to_param, :zproject => valid_attributes}, valid_session
        expect(assigns(:zproject)).to eq(zproject)
      end

      it "redirects to the zproject" do
        zproject = Zproject.create! valid_attributes
        put :update, {:id => zproject.to_param, :zproject => valid_attributes}, valid_session
        expect(response).to redirect_to(zproject)
      end
    end

    context "with invalid params" do
      it "assigns the zproject as @zproject" do
        zproject = Zproject.create! valid_attributes
        put :update, {:id => zproject.to_param, :zproject => invalid_attributes}, valid_session
        expect(assigns(:zproject)).to eq(zproject)
      end

      it "re-renders the 'edit' template" do
        zproject = Zproject.create! valid_attributes
        put :update, {:id => zproject.to_param, :zproject => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested zproject" do
      zproject = Zproject.create! valid_attributes
      expect {
        delete :destroy, {:id => zproject.to_param}, valid_session
      }.to change(Zproject, :count).by(-1)
    end

    it "redirects to the zprojects list" do
      zproject = Zproject.create! valid_attributes
      delete :destroy, {:id => zproject.to_param}, valid_session
      expect(response).to redirect_to(zprojects_url)
    end
  end

end
